### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/screaming-jellybaby#10]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.md
- [x] overview.md
- [x] learn.md

**Comment by bennuttall** [comment]
No software required, no hardware components missing, moved non-hardware stuff to `extras.md`. Just waiting on a cover image.

**Comment by lurch** [comment]
The cover image is now there, and this appears to be 'live' as the new format http://www.raspberrypi.org/learning/screaming-jellybaby/

Unfortunately the `3-5mmjack.jpg` image is missing on http://www.raspberrypi.org/learning/screaming-jellybaby/worksheet/ even though it gets displayed on https://github.com/raspberrypilearning/screaming-jellybaby/blob/master/worksheet.md

**Comment by bennuttall** [comment]
Ah, it was a relative link starting with `./images/` - this should be `images/`.

Fixed in 15b45b7e8f652b95edb359f47fa5ad45cb039aa2

**Comment by bennuttall** [comment]
It just needs checking over before this issue is closed

**Comment by lurch** [comment]
Just in case you didn't get auto-notified, I added some comments to the existing issues #5 and #6 .
(If you *did* get auto-notified, then apologies for this duplicate notification! ;-) )
