### ISSUE TITLE
Convert playing audio to pygame

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/screaming-jellybaby#12]
Should use `pygame.mixer` like [GPIO Music Box](https://github.com/raspberrypilearning/gpio-music-box)

Should also use a local audio file rather than downloaded one, like the music box.

**Comment by MissPhilbin** [comment]
Tried but for some reason the misc_burp.wav from sonic pi will not play with pygame. Reverted to os.system and omxplayer.
