### ISSUE TITLE
mp3 file

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/screaming-jellybaby#15]
I've created a Sounds folder, but I can't see a way to move the la.mp3 file into it (there's no edit icon when I open the file). Sorry if I'm being dense, but can anyone help?

**Comment by bennuttall** [comment]
I've just done it. You should just be able to move it into the right folder, then commit the change in the GitHub app.

**Comment by LornaLynch** [comment]
Thanks Ben!
