### ISSUE TITLE
Some extra notes may be needed.

### ISSUE THREAD

**Issue by keithellis74** [raspberrypilearning/screaming-jellybaby#5]
This code works because pins 3 & 5 have a pull up resistor.  Students and teachers may become confused if they try this on another GPIO pin and cannot get it to work.  It may be worth adding a note that this will only work with GPIO pins 3 & 5.  Or the PULL_UP_DOWN option could be used on other GPIO pins.

**Comment by lurch** [comment]
I guess this issue could be closed, now that the instructions say to connect to GPIO4 ?
Although I guess as the code is checking for `if GPIO.input(4) == False:` then presumably the internal pull-up should also be activated on GPIO4?

**Comment by lurch** [comment]
...and there's also a couple of places in the worksheet where it still refers to "pin 3" whereas GPIO4 is physical pin 7.

**Comment by MissPhilbin** [comment]
GPIO3 will be used thanks to pull_up. Added note about only using GPIO 3.

**Comment by lurch** [comment]
Again, this might just be me being overly pedantic, but worksheet.md still says:

"pin 3 of the General Purpose Input-Output (GPIO) header"

"pin 25 of the GPIO header" (this is the physical pin number, whereas when you're referring to 'pin 3' that's the GPIO number)

"set up the GPIO pins to use GPIO board pin numbers" (to me that implies `GPIO.BOARD` whereas you're actually now using `GPIO.BCM`)

"Set pin 3 on the GPIO header"
