### ISSUE TITLE
More information required

### ISSUE THREAD

**Issue by ryanteck** [raspberrypilearning/screaming-jellybaby#7]
From an actual test case I had one person have an issue with their code. 
Image or more visual way to show what Pins to use. It's very confusing sometimes.

Explain about using <tab> to indent. We had trouble troubleshooting due to them using spaces.

**Comment by bennuttall** [comment]
Thanks guys, we'll be adding @samalderhyde's GPIO diagrams shortly.

Yes @raspitv 4 spaces not tabs, I'll fix if it's still like that.

**Comment by ryanteck** [comment]
Are spaces suitable for kids to do?

**Comment by bennuttall** [comment]
You don't enter four spaces implicitly, you hit tab and your editor enters four spaces. IDLE is preconfigured to do this.
